/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Classes;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matheus Duarte
 */
public class telaCadastroS extends javax.swing.JFrame {
    
    private Servico s = new Servico();
    private BancoDadosServico bds = new BancoDadosServico();
    
    private static telaCadastroS telaCadastroServico;
    
    public telaCadastroS() {
        initComponents();
    }
    
    public static telaCadastroS gettelaCadastroS(){
        
        if(telaCadastroServico== null){
            
            telaCadastroServico = new telaCadastroS();
            
        }
        
        return telaCadastroServico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxtDesc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtHorasServ = new javax.swing.JTextField();
        lblValorHora = new javax.swing.JLabel();
        txtValorHora = new javax.swing.JTextField();
        btnCad = new javax.swing.JButton();
        btnCons = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabServico = new javax.swing.JTable();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("CADASTRAR SERVIÇO");

        lblDesc.setText("Descrição");

        atxtDesc.setColumns(20);
        atxtDesc.setRows(5);
        jScrollPane1.setViewportView(atxtDesc);

        jLabel2.setText("Horas Serviço");

        lblValorHora.setText("Valor Hora");

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnCons.setText("Consultar");
        btnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsActionPerformed(evt);
            }
        });

        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });

        tabServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descrição", "Horas/Serviço", "Valor/hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabServicoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabServico);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHorasServ, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorHora)
                                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCad)
                                .addGap(29, 29, 29)
                                .addComponent(btnCons)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemove)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlt))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDesc))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblValorHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorasServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCad)
                    .addComponent(btnCons)
                    .addComponent(btnRemove)
                    .addComponent(btnAlt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsActionPerformed
        consServico();
        listTabServico();
    }//GEN-LAST:event_btnConsActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        cadServico();
        listTabServico();
    }//GEN-LAST:event_btnCadActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        removeServico();
        listTabServico();     
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        atualizaServico();
        listTabServico();
    }//GEN-LAST:event_btnAltActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tabServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabServicoMouseClicked
        selectTab();
    }//GEN-LAST:event_tabServicoMouseClicked
    
    public void cadServico(){
        s = new Servico();
     
            s.setDescricao(atxtDesc.getText());
            s.setHorasTrabalhadas(Integer.parseInt(txtHorasServ.getText()));
            s.setValorHora(Float.parseFloat(txtValorHora.getText()));       

            s = BancoDadosServico.getServicoList().cadServico(s);

            if(s != null){
                JOptionPane.showMessageDialog(null,"Serviço cadastrado com sucesso", "Cadastro Serviço", JOptionPane.PLAIN_MESSAGE);
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(null, "Ja existe um serviço com este nome", "Cadastro Serviço", JOptionPane.ERROR_MESSAGE);
            }            
   
    }
     
     public void consServico(){
        s = new Servico();
        s.setDescricao(atxtDesc.getText());
               
        s = BancoDadosServico.getServicoList().consServico(s);
         
            if(s != null){
               txtHorasServ.setText(Integer.toString(s.getHorasTrabalhadas()));
               txtValorHora.setText(Float.toString(s.getValorHora()));
              
                JOptionPane.showMessageDialog(
                        null,
                        "Verifique os dados",
                        "Consulta Servoço pelo nome",
                        JOptionPane.PLAIN_MESSAGE
                );
            }
            else{
                       JOptionPane.showMessageDialog(
                        null,
                        "Não existe Serviço com este nome",
                        "Consulta Serviço pelo nome",
                        JOptionPane.ERROR_MESSAGE
                );
            }    
    }
     
    public void removeServico(){
        s = new Servico();
        s.setDescricao(atxtDesc.getText());
               
        s = BancoDadosServico.getServicoList().removeServico(s);
        
        if(s == null){
            JOptionPane.showMessageDialog(null,"Verifique os Dados", "Atualização pelo nome do serviço", JOptionPane.PLAIN_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Ja existe um serviço com este nome", "Atualização do serviço", JOptionPane.ERROR_MESSAGE);
        }
        limpar();
    }
    public void atualizaServico(){
        s = new Servico();
        s.setDescricao(atxtDesc.getText());
               
        s = BancoDadosServico.getServicoList().atualizaServico(s);
        if(s != null){
            
           txtHorasServ.setText(Integer.toString(s.getHorasTrabalhadas()));
           txtValorHora.setText(Float.toString(s.getValorHora()));
            
            JOptionPane.showMessageDialog(null,"Verifique os dados","Atualização do serviço pelo nome",JOptionPane.PLAIN_MESSAGE);
            limpar();
        }
        else{
                JOptionPane.showMessageDialog(null,"Não existe serviço com este nome","Alteração do serviço pelo nome",JOptionPane.ERROR_MESSAGE
            );
        }
    
    }
    public void listTabServico(){
        DefaultTableModel modelo = (DefaultTableModel)tabServico.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Servico s : BancoDadosServico.getServicoList().getListaServico()){
            modelo.insertRow(posLin, new Object[]{s.getDescricao(),s.getHorasTrabalhadas(),s.getValorHora()});
            posLin++;
        }
    }
    
    public void selectTab(){
        String valLin = "";
        int posLin = tabServico.getSelectedRow();
        
        for(int coluna = 0; coluna < tabServico.getColumnCount(); coluna++){
            valLin += tabServico.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna + 1 < tabServico.getColumnCount()){
                valLin += " - ";
            }
        }
        JOptionPane.showMessageDialog(
               null,
               "O serviço selecionado foi: \n"+valLin,
               "Resultado da seleção",
               JOptionPane.INFORMATION_MESSAGE
       );
    }
    
    
    public void limpar(){
        atxtDesc.setText("");
        txtHorasServ.setText("");
        txtValorHora.setText("");
  
        atxtDesc.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxtDesc;
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCons;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblValorHora;
    private javax.swing.JTable tabServico;
    private javax.swing.JTextField txtHorasServ;
    private javax.swing.JTextField txtValorHora;
    // End of variables declaration//GEN-END:variables
}
