/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Classes;

import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Duarte
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuPrincipal = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        mCCadastro = new javax.swing.JMenuItem();
        menuVeiculos = new javax.swing.JMenu();
        mVCadastro = new javax.swing.JMenuItem();
        menuServicos = new javax.swing.JMenu();
        mSCadastro = new javax.swing.JMenuItem();
        mPCadastro = new javax.swing.JMenuItem();
        menuNota = new javax.swing.JMenu();
        mNServico = new javax.swing.JMenuItem();
        mNPeca = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        menuClientes.setText("Clientes");

        mCCadastro.setText("Cadastrar Cliente");
        mCCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCCadastroActionPerformed(evt);
            }
        });
        menuClientes.add(mCCadastro);

        menuPrincipal.add(menuClientes);

        menuVeiculos.setText("Veiculos");

        mVCadastro.setText("Cadastrar Veiculo");
        mVCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVCadastroActionPerformed(evt);
            }
        });
        menuVeiculos.add(mVCadastro);

        menuPrincipal.add(menuVeiculos);

        menuServicos.setText("Serviços");

        mSCadastro.setText("Cadastrar Serviço");
        mSCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSCadastroActionPerformed(evt);
            }
        });
        menuServicos.add(mSCadastro);

        mPCadastro.setText("Cadastrar Peça");
        mPCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPCadastroActionPerformed(evt);
            }
        });
        menuServicos.add(mPCadastro);

        menuPrincipal.add(menuServicos);

        menuNota.setText("Nota");

        mNServico.setText("Listar Serviço");
        mNServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNServicoActionPerformed(evt);
            }
        });
        menuNota.add(mNServico);

        mNPeca.setText("Listar Peça");
        mNPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNPecaActionPerformed(evt);
            }
        });
        menuNota.add(mNPeca);

        menuPrincipal.add(menuNota);

        jMenu3.setText("Configuração");

        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        menuPrincipal.add(jMenu3);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mNServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNServicoActionPerformed
        abrirNotaServico();
    }//GEN-LAST:event_mNServicoActionPerformed

    private void mCCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCCadastroActionPerformed
        abrirClienteCad();
    }//GEN-LAST:event_mCCadastroActionPerformed

    private void mVCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVCadastroActionPerformed
        abrirVeiculoCad();
    }//GEN-LAST:event_mVCadastroActionPerformed

    private void mSCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSCadastroActionPerformed
        abrirServicoCad();
    }//GEN-LAST:event_mSCadastroActionPerformed

    private void mPCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPCadastroActionPerformed
        abrirServicoCon();
    }//GEN-LAST:event_mPCadastroActionPerformed

    private void mNPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNPecaActionPerformed
        abrirNotaPeca();
    }//GEN-LAST:event_mNPecaActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        sair();
    }//GEN-LAST:event_jMenuItem7ActionPerformed


    public void abrirClienteCad(){
       telaCadastroC.gettelaCadastroC().setVisible(true);
    }
    

     
   public void abrirVeiculoCad(){
       telaCadastroV.gettelaCadastroV().setVisible(true);
    } 
     
    
    public void abrirServicoCad(){
       telaCadastroS.gettelaCadastroS().setVisible(true);
    }
    
    public void abrirServicoCon(){
       telaCadastroP.gettelaConsultaS().setVisible(true);
    }
    
    public void abrirNotaPeca(){
       telaConsultaNPeca.gettelaConsultaNPeca().setVisible(true);
    }
    
    public void abrirNotaServico(){
       telaConsultaNServico.gettelaConsultaNServico().setVisible(true);
    }
    
    public void sair(){
            int respSair = JOptionPane.showConfirmDialog(
                        null,
                        "Deseja realmente sair?",
                        "Saida",
                        JOptionPane.YES_NO_OPTION
                );
        if(respSair == 0){
            //System.exit(0);
            dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem mCCadastro;
    private javax.swing.JMenuItem mNPeca;
    private javax.swing.JMenuItem mNServico;
    private javax.swing.JMenuItem mPCadastro;
    private javax.swing.JMenuItem mSCadastro;
    private javax.swing.JMenuItem mVCadastro;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuNota;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuServicos;
    private javax.swing.JMenu menuVeiculos;
    // End of variables declaration//GEN-END:variables
}
