/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Classes;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matheus Duarte
 */
public class telaCadastroP extends javax.swing.JFrame {
    
    private Peca p = new Peca();
    private BancoDadosPeca bdp = new BancoDadosPeca();

    
    private static telaCadastroP telaCadastroPeca;
    
    public telaCadastroP() {
        initComponents();
    }
    
    public static telaCadastroP gettelaConsultaS(){
        
        if(telaCadastroPeca == null){
            
            telaCadastroPeca= new telaCadastroP();
            
        }
        
        return telaCadastroPeca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPeca = new javax.swing.JLabel();
        txtPeca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();
        lblValorP = new javax.swing.JLabel();
        txtValorPeca = new javax.swing.JTextField();
        btnCad = new javax.swing.JButton();
        btnCons = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnAlt = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPeca = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("CADASTRAR PEÇA");

        lblPeca.setText("Peça");

        jLabel3.setText("Quantidade");

        lblValorP.setText("Valor Peça");

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnCons.setText("Consultar");
        btnCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsActionPerformed(evt);
            }
        });

        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnAlt.setText("Alterar");
        btnAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tabPeca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Peça", "Qtde", "Valor Peça"
            }
        ));
        tabPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPecaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabPeca);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValorPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorP))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemove)
                .addGap(18, 18, 18)
                .addComponent(btnAlt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeca)
                    .addComponent(jLabel3)
                    .addComponent(lblValorP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCad)
                    .addComponent(btnCons)
                    .addComponent(btnRemove)
                    .addComponent(btnAlt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        cadPeca();
        listTabPeca();
    }//GEN-LAST:event_btnCadActionPerformed

    private void btnConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsActionPerformed
        consPeca();
        listTabPeca();
    }//GEN-LAST:event_btnConsActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        removePeca();
        listTabPeca();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltActionPerformed
        atualizaPeca();
        listTabPeca();
    }//GEN-LAST:event_btnAltActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tabPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPecaMouseClicked
        selectTab();
    }//GEN-LAST:event_tabPecaMouseClicked

    public void cadPeca(){
        p = new Peca();
     
            p.setPeca(txtPeca.getText());
            p.setQuantidade(Integer.parseInt(txtQtde.getText()));
            p.setValorPeca(Float.parseFloat(txtValorPeca.getText()));       

            p = BancoDadosPeca.getPecaList().cadPeca(p);

            if(p != null){
                JOptionPane.showMessageDialog(null,"Peca cadastrada com sucesso", "Cadastro Peca", JOptionPane.PLAIN_MESSAGE);
                limpar();
            }
            else{
                JOptionPane.showMessageDialog(null, "Ja existe uma peca com este nome", "Cadastro Peça", JOptionPane.ERROR_MESSAGE);
            }            
   
    }
     
     public void consPeca(){
        p = new Peca();
        p.setPeca(txtPeca.getText());
          
        
        p = BancoDadosPeca.getPecaList().consPeca(p);
         
            if(p != null){
               txtQtde.setText(Integer.toString(p.getQuantidade()));
               txtValorPeca.setText(Float.toString(p.getValorPeca()));
              
                JOptionPane.showMessageDialog(
                        null,
                        "Verifique os dados",
                        "Consulta Peça pelo nome",
                        JOptionPane.PLAIN_MESSAGE
                );
            }
            else{
                       JOptionPane.showMessageDialog(
                        null,
                        "Não existe Peça com este nome",
                        "Consulta Peça pelo nome",
                        JOptionPane.ERROR_MESSAGE
                );
            }    
    }
     
    public void removePeca(){
        p = new Peca();
        p.setPeca(txtPeca.getText());
          
        p = BancoDadosPeca.getPecaList().removePeca(p);
        
        if(p == null){
            JOptionPane.showMessageDialog(null,"Verifique os Dados", "Atualização pelo nome da peça", JOptionPane.PLAIN_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Ja existe uma peça com este nome", "Atualização da peça", JOptionPane.ERROR_MESSAGE);
        }
        limpar();
    }
    public void atualizaPeca(){
        p = new Peca();
        p.setPeca(txtPeca.getText());
          
        p = BancoDadosPeca.getPecaList().atualizaPeca(p);
        if(p != null){
            
           txtQtde.setText(Integer.toString(p.getQuantidade()));
           txtValorPeca.setText(Float.toString(p.getValorPeca()));
            
            JOptionPane.showMessageDialog(null,"Verifique os dados","Atualização da Peça pelo nome",JOptionPane.PLAIN_MESSAGE);
             limpar();
        }
        else{
                   JOptionPane.showMessageDialog(null,"Não existe Peça com este nome","Alteração da Peça pelo nome",JOptionPane.ERROR_MESSAGE
            );
        }
    
    }
    public void listTabPeca(){
        DefaultTableModel modelo = (DefaultTableModel)tabPeca.getModel();
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Peca p : BancoDadosPeca.getPecaList().getListaPeca()){
            modelo.insertRow(posLin, new Object[]{p.getPeca(),p.getQuantidade(),p.getValorPeca()});
            posLin++;
        }
    }
    
    public void selectTab(){
        String valLin = "";
        int posLin = tabPeca.getSelectedRow();
        
        for(int coluna = 0; coluna < tabPeca.getColumnCount(); coluna++){
            valLin += tabPeca.getModel().getValueAt(posLin,coluna).toString();
            
            if(coluna + 1 < tabPeca.getColumnCount()){
                valLin += " - ";
            }
        }
        JOptionPane.showMessageDialog(
               null,
               "A peça selecionada foi: \n"+valLin,
               "Resultado da seleção",
               JOptionPane.INFORMATION_MESSAGE
       );
    }
    
    
    public void limpar(){
        txtPeca.setText("");
        txtQtde.setText("");
        txtValorPeca.setText("");
  
        txtPeca.requestFocus();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlt;
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCons;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPeca;
    private javax.swing.JLabel lblValorP;
    private javax.swing.JTable tabPeca;
    private javax.swing.JTextField txtPeca;
    private javax.swing.JTextField txtQtde;
    private javax.swing.JTextField txtValorPeca;
    // End of variables declaration//GEN-END:variables
}
